language: java
sudo: false

jdk:
  - openjdk8

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script:
  - mvn package

notifications:
  email:
    recipients:
      - koy@ko8e24.top
    on_success: always # default: change
    on_failure: always # default: always

